### ISSUE TITLE
Assert Event has Listener

### ISSUE THREAD

**Issue by jcergolj** [jasonmccreary/laravel-test-assertions#10]
Assert Event has Listener might be an assertion that others may use too.
My strategy for testing event is as follows: In a feature test, I assert that the event is fired. In a unit test, I assert everything related to the listener:
```
public function test_listener()
{
    $listener = new Listener();
    $listener->handle();

    $this->assert.....
}
```
What I need is a test in an EventServiceProviderTest class to assert that an event has a listener.

I copied and modified code from event list artican command:
```
public function assertEventHasListener($event, $listener)
{
        $events = [];

        foreach ($this->app->getProviders(EventServiceProvider::class) as $provider) {
            $providerEvents = array_merge_recursive(
                $provider->shouldDiscoverEvents() ? $provider->discoverEvents() : [], $provider->listens()
            );

            $events = array_merge_recursive($events, $providerEvents);
        }

        $this->assertTrue(in_array($listener, $events[$event]));
}
```

I can create a PR but I don't have access.

**Comment by jasonmccreary** [comment]
Could be interesting.

In order to contribute to an open source project on GitHub, it's best to make a fork. Review [this project](https://github.com/firstcontributions/first-contributions) for more details on making your first contribution.

**Comment by jcergolj** [comment]
Thanks for the guidance. I am contributing to an open source project for the first time.
PR submitted.

**Comment by jasonmccreary** [comment]
Nice work!

I'm going to close this issue and focus on the PR later today.
