### ISSUE TITLE
Asserting inverse of assertSoftDeleted

### ISSUE THREAD

**Issue by mikkoaf** [jasonmccreary/laravel-test-assertions#27]
Problem:

Asserting that a model has not been soft deleted is not a separate available test assertion 

https://laravel.com/docs/8.x/database-testing#assert-deleted

Solution:

There exists a ready solution which can be used. Adding this to the package could be helpful

```
public function assertModelNotSoftDeleted(Model $model)
{
    return $this->assertDatabaseHas($model->getTable(), [
        $model->getKeyName() => $model->getKey(),
        $model::DELETED_AT => null,
    ]);
}
```
Original snipped posted by
https://github.com/ImLiam
https://stackoverflow.com/questions/50328298/laravel-assert-not-soft-deleted-inverse-laravel-tests

**Comment by mikkoaf** [comment]
For some reason I ran to an issue where the static constant call fails.

```
Error: Undefined class constant 'DELETED_AT'
```
Fixed this in my scope hard-coding the `deleted_at` string.

**Comment by jasonmccreary** [comment]
Sure thing. Open a PR.
