### ISSUE TITLE
assertNotSoftDeleted declaration breaks in Laravel 8.62

### ISSUE THREAD

**Issue by shawnhooper** [jasonmccreary/laravel-test-assertions#30]
When Laravel Shift upgraded my repo to Laravel 8.62, this error appears in my build:

```
PHP Fatal error:  Declaration of JMac\Testing\Traits\AdditionalAssertions::assertNotSoftDeleted(Illuminate\Database\Eloquent\Model $model) must be compatible with Illuminate\Foundation\Testing\TestCase::assertNotSoftDeleted($table, array $data = [], $connection = null, $deletedAtColumn = 'deleted_at')
```

**Comment by jasonmccreary** [comment]
Yeah, this was just released 2 hours ago. This package will need to be updated to delegate or remove this method.

**Comment by shawnhooper** [comment]
@jasonmccreary 👍 Fair enough - Just wanted to report it.  Love these additional assertions :)

**Comment by jasonmccreary** [comment]
@shawnhooper, can you target `dev-v2` and see if it's all compatible? If so, I'll merge and tag as 2.0.

**Comment by shawnhooper** [comment]
@jasonmccreary Confirmed, that did built properly.   Thank you!

**Comment by jasonmccreary** [comment]
@shawnhooper, 2.0.0 has been tagged. Unfortunately since this was tagged after Shift's automation, most will need to manually update their dependency to `^2.0` when updating to Laravel 8.62.
