### ISSUE TITLE
Laravel 9.x support - illuminate/testing

### ISSUE THREAD

**Issue by arborrow** [jasonmccreary/laravel-test-assertions#35]
In preparation for Laravel 9:

Problem 1
    - illuminate/testing[v8.0.0, ..., v8.11.2] require php ^7.3 -> your php version (8.0.15) does not satisfy that requirement.
    - Root composer.json requires jasonmccreary/laravel-test-assertions ^2.0 -> satisfiable by jasonmccreary/laravel-test-assertions[v2.0.0].
    - Conclusion: don't install laravel/framework v9.0.0-beta.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.0.0-beta.3 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.0.0-beta.4 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.0.0-beta.1 (conflict analysis result)
    - jasonmccreary/laravel-test-assertions v2.0.0 requires **illuminate/testing ^8.0** -> satisfiable by illuminate/testing[v8.0.0, ..., 8.x-dev].
    - Only one of these can be installed: illuminate/testing[v8.0.0, ..., 8.x-dev], laravel/framework[v9.0.0-beta.1, ..., 9.x-dev]. laravel/framework replaces illuminate/testing and thus cannot coexist with it.
    - Root composer.json requires laravel/framework ^9.0 -> satisfiable by laravel/framework[v9.0.0-beta.1, ..., 9.x-dev].

**Comment by jasonmccreary** [comment]
Tagged in 2.1
