### ISSUE TITLE
assertActionUsesMiddleware and assertRouteUsesMiddleware doesn't respect excludedMiddleware

### ISSUE THREAD

**Issue by chrillep** [jasonmccreary/laravel-test-assertions#37]
if using withoutMiddleware
https://laravel.com/docs/9.x/middleware#excluding-middleware

the middleware will still show up as being used on
assertActionUsesMiddleware and assertRouteUsesMiddleware

**Comment by chrillep** [comment]
I'll give an example if needed.
just wanted to get my finding out of the way, before I forgot 😊

**Comment by jasonmccreary** [comment]
@chrillep, no, the issue is pretty straightforward. Probably won't get to the fix for a while though. Feel free to try a PR.

**Comment by chrillep** [comment]
> @chrillep, no, the issue is pretty straightforward. Probably won't get to the fix for a while though. Feel free to try a PR.

happily someone else fixed this 🚀

however the Fix isn't releases yet.
so until then using dev-master 😊

https://packagist.org/packages/jasonmccreary/laravel-test-assertions#dev-master


thanks fo making my testlife easier 🎉

**Comment by jasonmccreary** [comment]
@chrillep, is it working for you as expected on `dev-master`? If so, I'll close this and tag a release.

**Comment by chrillep** [comment]
> @chrillep, is it working for you as expected on `dev-master`? If so, I'll close this and tag a release.

yes it works. ty :) 👍🏼
