### ISSUE TITLE
using assertValidationRules in pest

### ISSUE THREAD

**Issue by AzadGh95** [jasonmccreary/laravel-test-assertions#39]
I used `assertValidationRules` from this package when I want to write a test for my request file:
```php
test('rules', function () {
    $actual = $this->subject->rules();
    $this->assertValidationRules([
        'mobile' => [
            'required',
        ],
    ], $actual);
});
```
But when I run `php test` get an error:
`Call to undefined method Tests\Unit\Http\Requests\MobileRequestTest::assertValidationRules()`

And I don't know what the reason is
Please help me.
Also thanks in advance.

**Comment by AzadGh95** [comment]
@jasonmccreary

**Comment by jasonmccreary** [comment]
My guess is you have not added the required trait to use these assertions.

**Comment by AzadGh95** [comment]
No, I added this `"jasonmccreary/laravel-test-assertions": "^2.1",` to **composer.json**

**Comment by jasonmccreary** [comment]
You need to add the trait too.

**Comment by AzadGh95** [comment]
I added this trait to `TestCase.php` too, but I have this error `Call to undefined method Tests\Unit\Http\Requests\MobileRequestTest::assertValidationRules()` yet!

**Comment by AzadGh95** [comment]
But when I'm this method in a unitTest , runs successfully! without any error.

**Comment by AzadGh95** [comment]
But when I'm using this method in an UnitTest , runs successfully! without any error.

**Comment by AzadGh95** [comment]
I fixed it,
just should add the directory name to **pest.php**
for example:
`uses(Tests\TestCase::class)->in('Feature','Unit');`
