### ISSUE TITLE
PHPUnit 10

### ISSUE THREAD

**Issue by ejunker** [jasonmccreary/laravel-test-assertions#41]
Please add support for PHPUnit 10
https://phpunit.de/announcements/phpunit-10.html

**Comment by jasonmccreary** [comment]
Probably won't happen soon. Feel free to open a PR to help get things started.

**Comment by jasonmccreary** [comment]
@zpwparsons got you. Point to `dev-master` and let me know how it goes.

**Comment by zpwparsons** [comment]
@jasonmccreary, dev-master is working 👍
