### ISSUE TITLE
Asserting a route uses a form request doesn't work with first class callables

### ISSUE THREAD

**Issue by phily245** [jasonmccreary/laravel-test-assertions#43]
I came across this when using [rector](https://getrector.com/) with the `LevetSetList::UPTO_PHP_82` rule to upgrade my code from PHP 8.1 to 8.2.

Rector converted my routes from this format:

```php
 Route::post('/', [SensorController::class, 'store'])
            ->name('store');
```

To use a first-class callable:

```php
Route::post('/', new (SensorController())->store(...))
            ->name('store');
```

My [pest](https://pestphp.com/) test then failed:

```php
it('validates using the correct form request', function () {
    $this->assertRouteUsesFormRequest('sensors.store', SensorRequest::class);
});
```

Upon closer inspection, inside `assertRouteUsesFormRequest` it looks for the controller action at https://github.com/jasonmccreary/laravel-test-assertions/blob/master/src/Traits/AdditionalAssertions.php#L14-L16, which is not set when using a first class callable, so the test then failed.

**Comment by jasonmccreary** [comment]
Probably not something I'll fix until Laravel is proven to support/use this syntax.

**Comment by phily245** [comment]
As a note for anyone else experiencing this, I fixed this by adding the following to my `rector.php` file:

```php
    $rectorConfig->skip([
        FirstClassCallableRector::class => [
            __DIR__ . '/routes',
        ],
    ]);
```
